### ISSUE TITLE
Recycle cookies for upstream request

### ISSUE THREAD

**Issue by ngeraedts** [tallarium/reverse_proxy_plug#125]
This plug does not recycle cookies at all when making the upstream request. Most other proxies will simply forward the entire cookie jar to the upstream request.

For example from Go:
* https://github.com/golang/go/blob/6db7480f5973ced97dfb08f949889e2ff108a492/src/net/http/httputil/reverseproxy.go#L234
* https://github.com/golang/go/blob/6db7480f5973ced97dfb08f949889e2ff108a492/src/net/http/request.go#L366-L395

More specifically, it looks like this plug recycles the cookie headers, but doesn't pass the correct option to HTTPoison/hackney:
https://hexdocs.pm/httpoison/readme.html#cookies

I'd be happy to submit the PR for this as I've already got a working copy locally.

**Comment by mwhitworth** [comment]
Checking out 7757d9a, I haven't been able to replicate any strange behaviours around cookies. I would have thought forwarding `Cookie` Is there a particular scenario that necessitated this?

I'll be pushing this in HTTPoison-specific adapter code for now.

P.S. I would have thought the larger issue would be rewriting the `domain` in the `Set-Cookie` - since cookies won't actually be sent by browsers on following requests if they are for different domains
